// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0-HNVpkicf8S5-r97dlzPS-enVi1m7zU',
    appId: '1:525216708103:web:6df31c7de569ee8a3ddca2',
    messagingSenderId: '525216708103',
    projectId: 'abiturient-minsk-analytics',
    authDomain: 'abiturient-minsk-analytics.firebaseapp.com',
    storageBucket: 'abiturient-minsk-analytics.appspot.com',
    measurementId: 'G-H90Q27BS88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTLHutRXAdz7rfyqgNc9LopGCFqd7NdZo',
    appId: '1:525216708103:android:46082a91f310ee273ddca2',
    messagingSenderId: '525216708103',
    projectId: 'abiturient-minsk-analytics',
    storageBucket: 'abiturient-minsk-analytics.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS1VCxqcG4SOutClQ0YoO1VOitgJh20Dw',
    appId: '1:525216708103:ios:797aff034e5cc6423ddca2',
    messagingSenderId: '525216708103',
    projectId: 'abiturient-minsk-analytics',
    storageBucket: 'abiturient-minsk-analytics.appspot.com',
    iosBundleId: 'com.example.flutterEduappNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS1VCxqcG4SOutClQ0YoO1VOitgJh20Dw',
    appId: '1:525216708103:ios:2b30e159c936fe673ddca2',
    messagingSenderId: '525216708103',
    projectId: 'abiturient-minsk-analytics',
    storageBucket: 'abiturient-minsk-analytics.appspot.com',
    iosBundleId: 'com.example.flutterEduappNew.RunnerTests',
  );
}
